# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhenoTips
email: support@phenotips.org
description: > # this means to ignore newlines until "baseurl:"
  PhenoTips™ is a software tool for collecting and analyzing phenotypic
  information for patients with genetic disorders.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phenotips.org" # the base hostname & protocol for your site
twitter_username: phenotips
github_username:  phenotips

# Build settings
markdown: kramdown
